let persones = [
    {
        id: 1,
        name: "Leonor",
        lastName: "Cremin",
        email: "Terence_Hirthe@yahoo.com",
        mobilePhone: "+989122473645",
        city: "Tehran",
        like: false,
    },
    {
        id: 2,
        name: "Deshaun",
        lastName: "Pollich",
        email: "Newell.Robel@hotmail.com",
        mobilePhone: "+989175902069",
        city: "Tehran",
        like: false,
    },
    {
        id: 3,
        name: "Grayson",
        lastName: "Luettgen",
        email: "Gregory.Stamm@hotmail.com",
        mobilePhone: "+989147925099",
        city: "Mashhad",
        like: false,
    },
    {
        id: 4,
        name: "Junior",
        lastName: "Keeling",
        email: "Haskell_Haley@hotmail.com",
        mobilePhone: "+989183049324",
        city: "Shiraz",
        like: false,
    },
    {
        id: 5,
        name: "Lorena",
        lastName: "Pouros",
        email: "Ambrose.Mayer@gmail.com",
        mobilePhone: "+989128505817",
        city: "Mashhad",
        like: true,
    },
    {
        id: 6,
        name: "Kasey",
        lastName: "Kessler",
        email: "Magali62@hotmail.com",
        mobilePhone: "+989192634950",
        city: "Mashhad",
        like: false,
    },
    {
        id: 7,
        name: "Jalyn",
        lastName: "Bergnaum",
        email: "Jada51@hotmail.com",
        mobilePhone: "+989119060046",
        city: "Tehran",
        like: false,
    },
    {
        id: 8,
        name: "Myrtis",
        lastName: "Smith",
        email: "Keven.Krajcik82@yahoo.com",
        mobilePhone: "+989174307076",
        city: "Isfahan",
        like: false,
    },
    {
        id: 9,
        name: "Casandra",
        lastName: "Kirlin",
        email: "Domenica49@hotmail.com",
        mobilePhone: "+989130582997",
        city: "Mashhad",
        like: false,
    },
    {
        id: 10,
        name: "Abe",
        lastName: "Larkin",
        email: "Gussie.Fritsch-Homenick@hotmail.com",
        mobilePhone: "+989111461335",
        city: "Shiraz",
        like: false,
    },
    {
        id: 11,
        name: "Emmalee",
        lastName: "Ebert",
        email: "Nolan42@hotmail.com",
        mobilePhone: "+989135086101",
        city: "Shiraz",
        like: false,
    },
    {
        id: 12,
        name: "Emilio",
        lastName: "Gusikowski",
        email: "Lucius.Cassin@hotmail.com",
        mobilePhone: "+989143004759",
        city: "Tabriz",
        like: false,
    },
    {
        id: 13,
        name: "Shania",
        lastName: "Connelly",
        email: "Ernestina62@gmail.com",
        mobilePhone: "+989136490659",
        city: "Mashhad",
        like: false,
    },
    {
        id: 14,
        name: "Patrick",
        lastName: "Borer",
        email: "Buster3@hotmail.com",
        mobilePhone: "+989114931372",
        city: "Shiraz",
        like: true,
    },
    {
        id: 15,
        name: "Jana",
        lastName: "Spinka",
        email: "Jaclyn_Hahn@gmail.com",
        mobilePhone: "+989112596675",
        city: "Tehran",
        like: false,
    },
    {
        id: 16,
        name: "Yazmin",
        lastName: "Cummings",
        email: "Reggie_Effertz@hotmail.com",
        mobilePhone: "+989154582399",
        city: "Shiraz",
        like: false,
    },
    {
        id: 17,
        name: "Ron",
        lastName: "Schmidt",
        email: "Mazie18@gmail.com",
        mobilePhone: "+989137555035",
        city: "Isfahan",
        like: false,
    },
    {
        id: 18,
        name: "Hilbert",
        lastName: "Wilkinson",
        email: "Ryann_Cartwright@yahoo.com",
        mobilePhone: "+989144792528",
        city: "Mashhad",
        like: false,
    },
    {
        id: 19,
        name: "Leslie",
        lastName: "Daugherty",
        email: "Carlee_Daniel70@hotmail.com",
        mobilePhone: "+989173960253",
        city: "Shiraz",
        like: false,
    },
    {
        id: 20,
        name: "Della",
        lastName: "Greenfelder",
        email: "Ransom.Wunsch65@yahoo.com",
        mobilePhone: "+989108976908",
        city: "Mashhad",
        like: false,
    },
    {
        id: 21,
        name: "Lucio",
        lastName: "Roberts",
        email: "Avery.Purdy3@gmail.com",
        mobilePhone: "+989183290467",
        city: "Mashhad",
        like: true,
    },
    {
        id: 22,
        name: "Ena",
        lastName: "Prohaska",
        email: "Zoila_Sipes6@yahoo.com",
        mobilePhone: "+989121355812",
        city: "Tabriz",
        like: false,
    },
    {
        id: 23,
        name: "Hilbert",
        lastName: "Gislason",
        email: "Maya_Koelpin35@gmail.com",
        mobilePhone: "+989172081508",
        city: "Tehran",
        like: true,
    },
    {
        id: 24,
        name: "Kenneth",
        lastName: "Lang-Hudson",
        email: "Phoebe61@hotmail.com",
        mobilePhone: "+989154275840",
        city: "Tabriz",
        like: true,
    },
    {
        id: 25,
        name: "Elbert",
        lastName: "Kutch",
        email: "Gerardo.Ankunding96@hotmail.com",
        mobilePhone: "+989198916993",
        city: "Tabriz",
        like: false,
    },
    {
        id: 26,
        name: "Maritza",
        lastName: "Rowe",
        email: "Lennie23@gmail.com",
        mobilePhone: "+989167851750",
        city: "Isfahan",
        like: false,
    },
    {
        id: 27,
        name: "Stella",
        lastName: "Schoen",
        email: "Alex.Mayer6@yahoo.com",
        mobilePhone: "+989169040198",
        city: "Tehran",
        like: false,
    },
    {
        id: 28,
        name: "Jerrold",
        lastName: "Harber",
        email: "Baylee49@gmail.com",
        mobilePhone: "+989188404796",
        city: "Tabriz",
        like: false,
    },
    {
        id: 29,
        name: "Fern",
        lastName: "Conroy",
        email: "Krystel50@hotmail.com",
        mobilePhone: "+989108062946",
        city: "Isfahan",
        like: false,
    },
    {
        id: 30,
        name: "Dawson",
        lastName: "Reilly",
        email: "Aric_Kirlin94@hotmail.com",
        mobilePhone: "+989148376865",
        city: "Isfahan",
        like: true,
    },
    {
        id: 31,
        name: "Estelle",
        lastName: "Schinner",
        email: "Johathan.Kassulke@yahoo.com",
        mobilePhone: "+989176324782",
        city: "Shiraz",
        like: false,
    },
    {
        id: 32,
        name: "Benjamin",
        lastName: "Hermiston",
        email: "Geovanni41@gmail.com",
        mobilePhone: "+989110895944",
        city: "Mashhad",
        like: true,
    },
    {
        id: 33,
        name: "Jessy",
        lastName: "Turner",
        email: "Jeffrey.Fahey@hotmail.com",
        mobilePhone: "+989130718771",
        city: "Mashhad",
        like: true,
    },
    {
        id: 34,
        name: "Cristobal",
        lastName: "Adams",
        email: "Hettie_Flatley78@yahoo.com",
        mobilePhone: "+989167612818",
        city: "Tehran",
        like: false,
    },
    {
        id: 35,
        name: "Vella",
        lastName: "Schmitt",
        email: "Kasandra23@hotmail.com",
        mobilePhone: "+989125206452",
        city: "Tabriz",
        like: true,
    },
    {
        id: 36,
        name: "Reba",
        lastName: "McDermott",
        email: "Lauryn.Wunsch@hotmail.com",
        mobilePhone: "+989185858659",
        city: "Isfahan",
        like: false,
    },
    {
        id: 37,
        name: "Marilyne",
        lastName: "Flatley",
        email: "Webster_Stroman@hotmail.com",
        mobilePhone: "+989190026837",
        city: "Mashhad",
        like: false,
    },
    {
        id: 38,
        name: "Wanda",
        lastName: "Conn",
        email: "Evan.Reinger@yahoo.com",
        mobilePhone: "+989104028907",
        city: "Tehran",
        like: false,
    },
    {
        id: 39,
        name: "Cielo",
        lastName: "Lubowitz",
        email: "Sabina.Ondricka@hotmail.com",
        mobilePhone: "+989105386820",
        city: "Shiraz",
        like: false,
    },
    {
        id: 40,
        name: "Kiley",
        lastName: "Rath",
        email: "Domingo_Gorczany@gmail.com",
        mobilePhone: "+989170849676",
        city: "Tehran",
        like: true,
    },
    {
        id: 41,
        name: "Gus",
        lastName: "Wunsch",
        email: "Dasia20@yahoo.com",
        mobilePhone: "+989184981804",
        city: "Shiraz",
        like: true,
    },
    {
        id: 42,
        name: "Muhammad",
        lastName: "Reinger",
        email: "Yasmine.Ziemann88@hotmail.com",
        mobilePhone: "+989188880851",
        city: "Isfahan",
        like: false,
    },
    {
        id: 43,
        name: "Roger",
        lastName: "Pagac",
        email: "Elias.Zieme@yahoo.com",
        mobilePhone: "+989109746061",
        city: "Tehran",
        like: false,
    },
    {
        id: 44,
        name: "Cecil",
        lastName: "Schimmel",
        email: "Edyth.Cummings28@gmail.com",
        mobilePhone: "+989185738050",
        city: "Tabriz",
        like: true,
    },
    {
        id: 45,
        name: "Justen",
        lastName: "Predovic",
        email: "Katharina82@hotmail.com",
        mobilePhone: "+989158138880",
        city: "Isfahan",
        like: false,
    },
    {
        id: 46,
        name: "Trey",
        lastName: "Larkin",
        email: "April_Bauch@hotmail.com",
        mobilePhone: "+989108251672",
        city: "Tabriz",
        like: false,
    },
    {
        id: 47,
        name: "Ricardo",
        lastName: "Leffler",
        email: "Stephany_Schmeler80@yahoo.com",
        mobilePhone: "+989119523557",
        city: "Tabriz",
        like: false,
    },
    {
        id: 48,
        name: "Torrance",
        lastName: "Bernier",
        email: "Jolie_Hackett51@yahoo.com",
        mobilePhone: "+989111128657",
        city: "Isfahan",
        like: true,
    },
    {
        id: 49,
        name: "Braeden",
        lastName: "Walsh-Prosacco",
        email: "Laney_Grimes@yahoo.com",
        mobilePhone: "+989146763741",
        city: "Isfahan",
        like: false,
    },
    {
        id: 50,
        name: "Ellen",
        lastName: "Kunde-Hermiston",
        email: "Edmond56@gmail.com",
        mobilePhone: "+989118039738",
        city: "Tabriz",
        like: true,
    },
];
const list = [
    {
        id: 1,
        name: "John",
        age: 20,
        city: "New York",
        country: "USA",
        like: false,
    },
    {
        id: 2,
        name: "Mary",
        age: 25,
        city: "London",
        country: "UK",
        like: true,
    },
    {
        id: 3,
        name: "Bob",
        age: 30,
        city: "Paris",
        country: "France",
        like: false,
    },
    {
        id: 4,
        name: "Joe",
        age: 35,
        city: "Berlin",
        country: "USA",
        like: true,
    },
    {
        id: 5,
        name: "Carl",
        age: 40,
        city: "Rome",
        country: "Italy",
        like: false,
    },
    {
        id: 6,
        name: "Liz",
        age: 45,
        city: "Madrid",
        country: "USA",
        like: true,
    },
    {
        id: 7,
        name: "Jane",
        age: 50,
        city: "Tokyo",
        country: "UK",
        like: true,
    },
    {
        id: 8,
        name: "Kate",
        age: 55,
        city: "Beijing",
        country: "UK",
        like: true,
    },
    {
        id: 9,
        name: "Jill",
        age: 60,
        city: "Moscow",
        country: "Italy",
        like: true,
    },
    {
        id: 10,
        name: "Ann",
        age: 65,
        city: "Delhi",
        country: "Italy",
        like: true,
    },
    {
        id: 11,
        name: "John",
        age: 20,
        city: "New York",
        country: "USA",
        like: false,
    },
    {
        id: 12,
        name: "Mary",
        age: 25,
        city: "London",
        country: "UK",
        like: true,
    },
    {
        id: 13,
        name: "Bob",
        age: 30,
        city: "Paris",
        country: "France",
        like: false,
    },
    {
        id: 14,
        name: "Joe",
        age: 35,
        city: "Berlin",
        country: "Italy",
        like: true,
    },
    {
        id: 15,
        name: "Carl",
        age: 40,
        city: "Rome",
        country: "Italy",
        like: false,
    },
    {
        id: 16,
        name: "Liz",
        age: 45,
        city: "Madrid",
        country: "Italy",
        like: true,
    },
    {
        id: 17,
        name: "Jane",
        age: 50,
        city: "Tokyo",
        country: "China",
        like: true,
    },
    {
        id: 18,
        name: "Kate",
        age: 55,
        city: "Beijing",
        country: "China",
        like: true,
    },
    {
        id: 19,
        name: "Jill",
        age: 60,
        city: "Moscow",
        country: "China",
        like: true,
    },
    {
        id: 20,
        name: "Ann",
        age: 65,
        city: "Delhi",
        country: "China",
        like: true,
    },
    {
        id: 21,
        name: "John",
        age: 20,
        city: "San Francisco",
        country: "USA",
        like: false,
    },
    {
        id: 22,
        name: "Mary",
        age: 55,
        city: "Manchester",
        country: "UK",
        like: true,
    },
    {
        id: 23,
        name: "Bob",
        age: 30,
        city: "Paris",
        country: "France",
        like: false,
    },
    {
        id: 24,
        name: "Bob",
        age: 30,
        city: "leon",
        country: "France",
        like: true,
    },
    //implement 15 person down
];

// creat array with
export function UpdateList(arr) {
    persones = arr;
    return persones;
}

export function getPersones() {
    return persones;
}

export function getPersone(id) {
    return persones.find((p) => p.id === id);
}

export function savePersone(persone) {
    let personeInDb = persones.find((p) => p.id == persone.Id) || {};
    console.log(personeInDb);
    personeInDb.name = persone.Name;
    personeInDb.lastName = persone.Lastname;
    personeInDb.email = persone.Email;
    personeInDb.mobilePhone = persone.Mobilephone;
    personeInDb.city = persone.City;
    personeInDb.like = false;

    if (!personeInDb.id) {
        personeInDb.id = Date.now();
        persones.push(personeInDb);
    }
    return personeInDb;
}
